### ISSUE TITLE
Tracking

### ISSUE THREAD

**Issue by concerned-user** [nurupo/ProjectTox-Qt-GUI#131]
I don't know if this is the correct place to ask this, but I don't know what other ways to contact you and this is a very serious issue with the Tox project. irungentoo deleted these concerns from the toxcore repository, so this I have to bring it up here instead. irungentoo is enforcing censorship on this. I hope you don't censor these concerns as other members of the Tox Foundation are doing.

Recently @Proplex left the project over the following discussion: https://gist.github.com/irungentoo/5af26f5edefcdb7eac72

Soon after, I came to the following intriguing link: https://mail.tox.im/prolapse.txt

Can you explain why the Tox Foundation is tracking when Proplex visits your websites?
For an organization that says it is privacy-respecting, freedom lover and whatnot, this is highly contradictory and raise many concerns.

PS: sorry if this isn't the right repository, but this issue really needs to be discussed and it is relevant to the Tox project as a whole.

EDIT:
**Red alert:** The document of https://mail.tox.im/prolapse.txt has been edited. Really looks like someone from the Tox Foundation is trying to cover this up. Hopefully the service archive.today let us see what was previously hosted on the website.
https://archive.today/KkSWp

**Comment by concerned-user** [comment]
https://gist.github.com/urras/ba792274f5aaf662a082

**Comment by nurupo** [comment]
This is not relevant to the code that is hosted in this repository. If you wanted to contact me, you could do so through https://github.com/nurupo/ProjectTox-Qt-GUI#contact .

In the future, please refrain from spamming multiple repositories with the same message, that's not nice at all.

Also, it seems that the issue in question is being discussed in one of multiple issues you have created, so there is no need for this one.
